-- A7 Test Asset Pre-injection (Migration 010)
-- Stores structured test assets generated by A7, injected into A9 context, executed by A11

CREATE TABLE IF NOT EXISTS test_assets (
    id              SERIAL PRIMARY KEY,
    req_id          UUID NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,

    -- Test Asset Structure
    unit_tests      JSONB NOT NULL DEFAULT '[]',           -- Array of unit test objects
    integration_tests JSONB NOT NULL DEFAULT '[]',         -- Array of integration test objects
    e2e_tests       JSONB NOT NULL DEFAULT '[]',           -- Array of e2e test objects
    visual_tests    JSONB NOT NULL DEFAULT '[]',           -- Array of visual test objects

    -- Coverage Targets
    coverage_targets JSONB NOT NULL DEFAULT '{"overall": 0.8, "branches": 0.75, "lines": 0.85}',

    -- Metadata
    source          VARCHAR(50) DEFAULT 'a7_generator',    -- a7_generator | manual | imported
    total_cases     INT DEFAULT 0,
    priority_distribution JSONB,                           -- {"P0": 5, "P1": 10, "P2": 3}

    -- Versioning
    version         INT DEFAULT 1,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_test_assets_req_id ON test_assets(req_id DESC);
CREATE INDEX IF NOT EXISTS idx_test_assets_created ON test_assets(created_at DESC);


-- Test Execution Results from A11
CREATE TABLE IF NOT EXISTS test_results (
    id              SERIAL PRIMARY KEY,
    req_id          UUID NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,
    test_asset_id   INT NOT NULL REFERENCES test_assets(id) ON DELETE CASCADE,

    -- Test Categorization
    test_type       VARCHAR(50) NOT NULL,  -- unit | integration | e2e | visual
    test_name       VARCHAR(255) NOT NULL,
    test_file       VARCHAR(500),

    -- Execution Results
    status          VARCHAR(30) NOT NULL,  -- passed | failed | skipped | error
    duration_ms     INT,
    error_message   TEXT,

    -- Coverage Data
    line_coverage   FLOAT,                 -- 0.0-1.0
    branch_coverage FLOAT,                 -- 0.0-1.0
    statement_coverage FLOAT,              -- 0.0-1.0

    -- Mutation Testing
    mutation_score  FLOAT,                 -- 0.0-1.0 (from Stryker)
    mutations_killed INT,
    mutations_total INT,

    -- Metadata
    executed_by     VARCHAR(50),           -- Agent ID (A11)
    execution_round INT DEFAULT 1,         -- 1=initial, 2+=re-run after augmentation
    artifacts_json  JSONB,                 -- Links to logs, screenshots, etc.

    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_test_results_req ON test_results(req_id);
CREATE INDEX IF NOT EXISTS idx_test_results_status ON test_results(status);
CREATE INDEX IF NOT EXISTS idx_test_results_asset ON test_results(test_asset_id);
CREATE INDEX IF NOT EXISTS idx_test_results_type ON test_results(test_type);


-- TDD Session Tracking
CREATE TABLE IF NOT EXISTS tdd_sessions (
    id              SERIAL PRIMARY KEY,
    req_id          UUID NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,
    test_asset_id   INT NOT NULL REFERENCES test_assets(id) ON DELETE CASCADE,

    -- Session State
    status          VARCHAR(30) DEFAULT 'active',          -- active | completed | failed
    phase           VARCHAR(30),                           -- test_generation | context_injection | tdd_development | test_execution | coverage_augmentation

    -- Coverage Tracking
    initial_coverage FLOAT,
    target_coverage FLOAT DEFAULT 0.8,
    final_coverage  FLOAT,
    coverage_gap    FLOAT,                 -- target - final (negative if exceeded)

    -- Results Summary
    tests_generated INT,
    tests_passed    INT,
    tests_failed    INT,
    tests_augmented INT DEFAULT 0,         -- Additional tests added by A11 Critic

    -- Timing
    started_at      TIMESTAMPTZ DEFAULT NOW(),
    completed_at    TIMESTAMPTZ,
    duration_seconds INT,

    -- Workflow Reference
    workflow_run_id VARCHAR(255),          -- Temporal workflow run ID

    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tdd_sessions_req ON tdd_sessions(req_id);
CREATE INDEX IF NOT EXISTS idx_tdd_sessions_status ON tdd_sessions(status);
CREATE INDEX IF NOT EXISTS idx_tdd_sessions_asset ON tdd_sessions(test_asset_id);
