[mypy]
# Mypy configuration for Inner Auditor

# Imports
follow_imports = silent
ignore_missing_imports = True

# Output
pretty = True
show_column_numbers = True
show_error_codes = True
show_error_context = True

# Strictness
strict = False
warn_return_any = True
warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_no_return = True

# Type checking
check_untyped_defs = True
disallow_incomplete_defs = False
disallow_untyped_defs = False
disallow_any_generics = False

# Exclude patterns
exclude = (?x)(
    ^setup\.py$
    | ^test_
    | ^__pycache__
  )
