"""
Compose Generator — generates docker-compose.test.yaml from a dependency list.

Real implementation would:
  - Use Jinja2 templates for docker-compose.yml generation
  - Support compose v3.x+ with profiles, healthchecks, depends_on conditions
  - Inject test-specific overrides (ports, environment, volumes)
  - Generate convenience scripts (docker-compose -f compose.test.yaml up -d)
  - Validate port availability against localhost before generation
"""

import logging
import random
import string
from typing import Any, Dict, List

logger = logging.getLogger(__name__)


class ComposeGenerator:
    """Generate a docker-compose.test.yaml from an analyzed dependency list."""

    def generate(self, dependencies: list, project_name: str) -> dict:
        """
        Generate a docker-compose.test.yaml file from service dependencies.

        Args:
            dependencies: List of service dicts (output from DependencyAnalyzer.analyze).
            project_name: Docker Compose project name (used in container naming).

        Returns:
            {
                compose_yaml: str,          # full YAML content
                file_path: str,             # suggested file path
                services_count: int,        # number of services defined
                start_command: str,         # suggested docker-compose up command
            }
        """
        if not dependencies:
            logger.warning("No dependencies provided; generating minimal compose file.")
            return {
                "compose_yaml": "version: '3.8'\nservices: {}\n",
                "file_path": "docker-compose.test.yaml",
                "services_count": 0,
                "start_command": "docker-compose -f docker-compose.test.yaml up -d",
            }

        # Parse the dependency structure — may be a services list directly or
        # the full analysis result dict
        services_input = dependencies
        volumes_input: List[Dict[str, str]] = []
        networks_input: List[Dict[str, str]] = []

        if isinstance(dependencies, dict):
            services_input = dependencies.get("services", dependencies)
            volumes_input = dependencies.get("volumes", [])
            networks_input = dependencies.get("networks", [])

        logger.info(
            "Generating docker-compose.test.yaml for project '%s' with %d services",
            project_name,
            len(services_input),
        )

        lines: List[str] = []
        lines.append("# Auto-generated docker-compose.test.yaml")
        lines.append(f"# Project: {project_name}")
        lines.append("# Generated by A7 Test Case Generator — ComposeGenerator")
        lines.append("")
        lines.append("version: '3.8'")
        lines.append("")
        lines.append("services:")

        for svc in services_input:
            svc_name = svc.get("name", "unknown")
            svc_type = svc.get("type", "custom")
            svc_version = svc.get("version", "latest")
            svc_port = svc.get("port", 8080)
            env_vars = svc.get("env_vars", {})
            extra_volumes = svc.get("volumes", [])
            depends_on = svc.get("depends_on", [])

            # Derive a dynamic host port to avoid collisions
            host_port = self._allocate_port(svc_port)

            lines.append(f"  {svc_name}:")
            lines.append(f"    image: {svc_type}:{svc_version}")
            lines.append(f'    container_name: {project_name}_{svc_name}')

            if env_vars:
                lines.append(f"    environment:")
                for k, v in env_vars.items():
                    lines.append(f"      {k}: {v}")

            lines.append(f"    ports:")
            lines.append(f'      - "{host_port}:{svc_port}"')

            # Add healthcheck for database services
            if svc_type in ("postgres", "mysql"):
                lines.append(f"    healthcheck:")
                if svc_type == "postgres":
                    lines.append(f'      test: ["CMD-SHELL", "pg_isready -U test_user"]')
                else:
                    lines.append(f'      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]')
                lines.append(f'      interval: 10s')
                lines.append(f'      timeout: 5s')
                lines.append(f'      retries: 5')

            # Volumes
            all_volumes = list(extra_volumes)
            if svc_type in ("postgres", "mysql"):
                all_volumes.append(f"{svc_name}_data:/var/lib/{svc_type}/data")
            if all_volumes:
                lines.append(f"    volumes:")
                for v in all_volumes:
                    lines.append(f"      - {v}")

            # Depends on
            if depends_on:
                lines.append(f"    depends_on:")
                for dep in depends_on:
                    lines.append(f"      {dep}:")
                    lines.append(f"        condition: service_healthy")

            # Network
            lines.append(f"    networks:")
            lines.append(f"      - test-network")
            lines.append("")

        # --- Volumes section ---
        if volumes_input:
            lines.append("volumes:")
            for vol in volumes_input:
                vol_name = vol.get("name", "data_volume")
                vol_driver = vol.get("driver", "local")
                lines.append(f"  {vol_name}:")
                lines.append(f"    driver: {vol_driver}")
            lines.append("")

        # --- Networks section ---
        lines.append("networks:")
        lines.append("  test-network:")
        lines.append("    driver: bridge")
        lines.append("")

        compose_yaml = "\n".join(lines)

        # Generate safe project name slug
        slug = "".join(c if c.isalnum() or c in "-_" else "_" for c in project_name).lower()

        file_path = "docker-compose.test.yaml"
        start_command = f"docker compose -f docker-compose.test.yaml -p {slug}_test up -d"

        logger.info(
            "Compose file generated: %d services, %d chars, path=%s",
            len(services_input),
            len(compose_yaml),
            file_path,
        )

        return {
            "compose_yaml": compose_yaml,
            "file_path": file_path,
            "services_count": len(services_input),
            "start_command": start_command,
        }

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _allocate_port(self, base_port: int) -> int:
        """
        Allocate a host port for a service.

        In production this would check for port conflicts via netstat / ss.
        For the stub we offset by a random small amount to simulate
        non-conflicting allocation.
        """
        offset = random.randint(0, 100)
        return base_port + offset
