"""
Seed Data Generator — uses an LLM (stub) to generate realistic SQL seed data from an ERD.

Real implementation would:
  - Call an LLM (Claude / GPT) with the ERD schema as context
  - Prompt for domain-realistic data (real names, addresses, product names)
  - Support locale-aware generation (en_US, zh_CN, etc.)
  - Handle foreign-key relationships to ensure referential integrity
  - Generate INSERT statements with ON CONFLICT handling
  - Batch INSERTs for performance (multi-row VALUES clauses)
"""

import logging
import random
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List

logger = logging.getLogger(__name__)


class SeedDataGenerator:
    """Generate realistic SQL seed data from an ERD using an LLM backend (stubbed)."""

    # Domain-specific sample pools for realistic data generation
    _SAMPLE_DATA = {
        "first_name": ["Alice", "Bob", "Charlie", "Diana", "Eve", "Frank", "Grace"],
        "last_name": ["Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller"],
        "email_domains": ["example.com", "test.org", "corp.dev", "mail.net"],
        "product_names": [
            "Wireless Mouse", "Mechanical Keyboard", "USB-C Hub",
            "27\" Monitor", "Laptop Stand", "Webcam Pro", "Desk Lamp",
        ],
        "status_values": ["active", "inactive", "pending", "suspended", "archived"],
        "cities": ["New York", "London", "Tokyo", "Berlin", "Sydney", "Toronto", "Singapore"],
    }

    async def generate(self, erd: dict, row_count: int = 50) -> dict:
        """
        Generate realistic SQL seed data from an ERD.

        Args:
            erd: Entity-Relationship Diagram dict with entities and relationships.
            row_count: Target number of rows per table (default 50).

        Returns:
            {
                sql_file: str,            # complete SQL with INSERT statements
                tables_populated: int,    # number of tables with seed data
                total_rows: int,          # total rows across all tables
                realistic: bool,          # whether realistic data was used (always True)
            }
        """
        entities = erd.get("entities", [])
        if not entities:
            logger.warning("No entities in ERD — generating empty seed data")
            return {
                "sql_file": "-- No entities found in ERD\n",
                "tables_populated": 0,
                "total_rows": 0,
                "realistic": True,
            }

        logger.info(
            "Generating seed data for %d entities, ~%d rows each",
            len(entities),
            row_count,
        )

        lines: List[str] = [
            "-- ============================================================",
            "-- Auto-generated seed data",
            "-- Generated by A7 Test Case Generator — SeedDataGenerator",
            f"-- Tables: {len(entities)}, target rows per table: {row_count}",
            "-- ============================================================",
            "",
            "BEGIN;",
            "",
        ]

        tables_populated = 0
        total_rows = 0

        # Process entities in dependency order (simplified: alphabetical by name)
        sorted_entities = sorted(entities, key=lambda e: e.get("name", ""))

        for entity in sorted_entities:
            table_name = entity.get("name", entity.get("table", "unknown_table"))
            fields = entity.get("fields", entity.get("columns", []))

            if not fields:
                continue

            insert_lines = self._generate_inserts(table_name, fields, row_count)
            lines.extend(insert_lines)
            tables_populated += 1
            total_rows += row_count

        lines.append("")
        lines.append("COMMIT;")
        lines.append("")

        sql_file = "\n".join(lines)

        logger.info(
            "Seed data generated: %d tables, %d total rows, %d chars",
            tables_populated,
            total_rows,
            len(sql_file),
        )

        return {
            "sql_file": sql_file,
            "tables_populated": tables_populated,
            "total_rows": total_rows,
            "realistic": True,
        }

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _generate_inserts(
        self, table_name: str, fields: list, row_count: int
    ) -> list:
        """Generate INSERT statements for a single table."""
        # Filter out auto-generated PK columns (serials, auto_increment ints with pk)
        insert_fields = [
            f for f in fields
            if not self._is_auto_generated(f)
        ]

        if not insert_fields:
            # Table with only auto-gen columns — insert one row with defaults
            return [
                f"-- Table: {table_name} (all columns auto-generated)",
                f"INSERT INTO {table_name} DEFAULT VALUES;",
                "",
            ]

        col_names = ", ".join(f.get("name") for f in insert_fields)
        lines = [f"-- Seed data for {table_name}"]
        lines.append(f"INSERT INTO {table_name} ({col_names}) VALUES")

        value_rows = []
        for i in range(row_count):
            values = self._generate_row_values(insert_fields, i)
            suffix = "," if i < row_count - 1 else ";"
            value_rows.append(f"  ({values}){suffix}")

        lines.extend(value_rows)
        lines.append("")

        return lines

    def _is_auto_generated(self, field: dict) -> bool:
        """Check if a field is auto-generated (serial, auto-increment PK)."""
        ftype = field.get("type", "").lower()
        pk = field.get("pk", field.get("primary_key", False))
        default = field.get("default", "")

        # Serial types in PostgreSQL
        if ftype in ("serial", "bigserial", "smallserial"):
            return True
        # AUTO_INCREMENT in MySQL
        if pk and "auto_increment" in ftype:
            return True
        # UUID with gen_random_uuid() default
        if ftype == "uuid" and "gen_random" in str(default).lower():
            return True
        # IDENTITY columns
        if "identity" in ftype.lower():
            return True

        return False

    def _generate_row_values(self, fields: list, row_index: int) -> str:
        """Generate a single row's VALUES clause with realistic data."""
        values = []
        for field in fields:
            val = self._generate_field_value(field, row_index)
            values.append(val)
        return ", ".join(values)

    def _generate_field_value(self, field: dict, row_index: int) -> str:
        """Generate a realistic value for a single field."""
        fname = field.get("name", "").lower()
        ftype = field.get("type", "").lower()
        fmt = field.get("format", "")
        nullable = field.get("nullable", True)

        # Occasionally produce NULL for nullable fields
        if nullable and row_index % 20 == 0 and row_index > 0:
            return "NULL"

        # --- String-like types ---
        if ftype in ("varchar", "text", "char", "character varying", "string", "nvarchar"):
            return self._string_value(fname, row_index)

        # --- Integer types ---
        if ftype in ("integer", "int", "int4", "bigint", "int8", "smallint", "int2", "serial", "bigserial"):
            return self._integer_value(fname, row_index)

        # --- Numeric / decimal ---
        if ftype in ("numeric", "decimal", "float", "double precision", "real", "float8", "float4"):
            return self._numeric_value(fname, row_index)

        # --- Boolean ---
        if ftype in ("boolean", "bool"):
            return "TRUE" if row_index % 2 == 0 else "FALSE"

        # --- Date / time ---
        if ftype in ("date", "timestamp", "timestamptz", "datetime", "timestamp without time zone", "timestamp with time zone"):
            return self._date_value(ftype, row_index)

        # --- UUID ---
        if ftype == "uuid":
            return f"'00000000-0000-0000-0000-{row_index:012d}'"

        # --- JSON / JSONB ---
        if ftype in ("json", "jsonb"):
            return f"'{{\"key\": \"value_{row_index}\"}}'::jsonb"

        # --- Enum-like (fallback) ---
        if "enum" in ftype or fname.endswith("status") or fname.endswith("state"):
            return self._enum_value(row_index)

        # Default
        return f"'value_{row_index}'"

    def _string_value(self, field_name: str, row_index: int) -> str:
        """Generate a realistic string value based on field name heuristics."""
        pool = self._SAMPLE_DATA
        idx = row_index % 7  # cycle through sample values

        if "email" in field_name:
            return f"'{pool['first_name'][idx].lower()}.{pool['last_name'][idx].lower()}@{pool['email_domains'][idx % len(pool['email_domains'])]}'"
        if "first_name" in field_name or "given_name" in field_name or "fname" == field_name:
            return f"'{pool['first_name'][idx]}'"
        if "last_name" in field_name or "surname" in field_name or "lname" == field_name:
            return f"'{pool['last_name'][idx]}'"
        if "name" in field_name:
            return f"'{pool['product_names'][idx % len(pool['product_names'])]}'"
        if "city" in field_name:
            return f"'{pool['cities'][idx]}'"
        if "phone" in field_name:
            return f"'+1-555-{1000 + row_index:04d}'"
        if "url" in field_name or "website" in field_name:
            return f"'https://example{idx}.com/page{row_index}'"
        if "description" in field_name or "desc" in field_name:
            return f"'Description for item {row_index} — lorem ipsum dolor sit amet.'"

        return f"'sample_{field_name}_{row_index}'"

    def _integer_value(self, field_name: str, row_index: int) -> str:
        """Generate a realistic integer."""
        if "age" in field_name:
            return str(18 + (row_index % 60))
        if "year" in field_name:
            return str(2020 + (row_index % 6))
        if "count" in field_name or "quantity" in field_name or "qty" in field_name:
            return str(1 + (row_index % 100))
        if "price" in field_name or "amount" in field_name or "cents" in field_name:
            return str((1 + row_index) * 100)  # stored as cents
        if "id" in field_name and field_name != "id":
            # Foreign key — cycle through referenced IDs
            return str(1 + (row_index % 20))
        if "priority" in field_name or "rank" in field_name or "level" in field_name:
            return str(row_index % 5 + 1)
        return str(row_index + 1)

    def _numeric_value(self, field_name: str, row_index: int) -> str:
        """Generate a realistic decimal/float."""
        if "price" in field_name or "amount" in field_name or "cost" in field_name:
            return f"{9.99 + (row_index * 1.5):.2f}"
        if "rate" in field_name or "ratio" in field_name:
            return f"{random.uniform(0.1, 5.0):.2f}"
        if "latitude" in field_name:
            return f"{random.uniform(-90, 90):.6f}"
        if "longitude" in field_name:
            return f"{random.uniform(-180, 180):.6f}"
        return f"{random.uniform(1.0, 1000.0):.2f}"

    def _date_value(self, ftype: str, row_index: int) -> str:
        """Generate a realistic date / timestamp."""
        base = datetime(2024, 1, 1, tzinfo=timezone.utc)
        offset = timedelta(days=row_index * 3, hours=row_index)
        dt = base + offset

        if ftype == "date":
            return f"'{dt.strftime('%Y-%m-%d')}'"
        # timestamp
        return f"'{dt.isoformat()}'"

    def _enum_value(self, row_index: int) -> str:
        """Pick from a pool of status-like values."""
        pool = self._SAMPLE_DATA["status_values"]
        return f"'{pool[row_index % len(pool)]}'"
