"""
Prometheus Metrics for Test Asset Pre-injection (Task #36)

Tracks:
- Test assets generated and injected
- TDD development cycle timing
- Test execution results
- Coverage metrics and gaps
- Test augmentation cycles
"""

from prometheus_client import Counter, Gauge, Histogram, Summary
import logging

logger = logging.getLogger(__name__)

# ========== COUNTERS ==========

# A7 Test Asset Generation
TEST_ASSETS_GENERATED = Counter(
    'test_assets_generated_total',
    'Total test assets generated by A7',
    ['asset_type']  # unit_tests, integration_tests, e2e_tests, visual_tests
)

TEST_ASSETS_INJECTED = Counter(
    'test_assets_injected_total',
    'Total test assets injected into A9 context',
    ['req_id']
)

# A9 TDD Development
TDD_DEV_COMPLETIONS = Counter(
    'tdd_dev_completions_total',
    'Total TDD development phases completed by A9',
    ['status']  # success, failure
)

# A11 Test Execution
TEST_EXECUTIONS = Counter(
    'test_executions_total',
    'Total test executions by A11',
    ['test_type', 'status']  # test_type: unit/integration/e2e/visual, status: passed/failed
)

TEST_AUGMENTATIONS = Counter(
    'test_augmentations_total',
    'Total test augmentation cycles by A11 Critic',
    ['reason']  # coverage_gap, mutation_score, uncovered_branch
)

COVERAGE_TARGET_MET = Counter(
    'coverage_target_met_total',
    'Total times coverage target was met',
    ['req_id']
)

# Workflow Progress
TDD_WORKFLOW_COMPLETIONS = Counter(
    'tdd_workflow_completions_total',
    'Total TDD workflow completions',
    ['status']  # completed, failed, augmented
)

# ========== GAUGES ==========

# Coverage Metrics
TDD_TEST_PASS_RATE = Gauge(
    'tdd_test_pass_rate',
    'Test pass rate in TDD cycle',
    ['req_id', 'phase']  # phase: initial, augmented
)

A11_COVERAGE_CURRENT = Gauge(
    'a11_coverage_current',
    'Current code coverage percentage',
    ['req_id', 'coverage_type']  # coverage_type: overall, line, branch, statement
)

A11_COVERAGE_GAP = Gauge(
    'a11_coverage_gap',
    'Gap between current and target coverage',
    ['req_id']
)

A11_COVERAGE_TARGET = Gauge(
    'a11_coverage_target',
    'Target coverage percentage',
    ['req_id']
)

# Test Asset Composition
TEST_ASSET_DISTRIBUTION = Gauge(
    'test_asset_distribution',
    'Distribution of test assets by type',
    ['req_id', 'test_type']  # test_type: unit, integration, e2e, visual
)

# Timing
TDD_CYCLE_DURATION_SECONDS = Gauge(
    'tdd_cycle_duration_seconds',
    'Duration of complete TDD cycle in seconds',
    ['req_id']
)

A7_GENERATION_DURATION_SECONDS = Gauge(
    'a7_generation_duration_seconds',
    'Duration of A7 test asset generation in seconds',
    ['req_id']
)

A9_TDD_DEVELOPMENT_DURATION_SECONDS = Gauge(
    'a9_tdd_development_duration_seconds',
    'Duration of A9 TDD development phase in seconds',
    ['req_id']
)

A11_TEST_EXECUTION_DURATION_SECONDS = Gauge(
    'a11_test_execution_duration_seconds',
    'Duration of A11 test execution in seconds',
    ['req_id']
)

# ========== HISTOGRAMS ==========

# Test Execution Timing
TEST_EXECUTION_DURATION = Histogram(
    'test_execution_duration_seconds',
    'Test execution duration by type',
    ['test_type'],
    buckets=(0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0, 300.0)
)

COVERAGE_MEASUREMENT_DURATION = Histogram(
    'coverage_measurement_duration_seconds',
    'Time to measure code coverage',
    buckets=(0.5, 1.0, 2.0, 5.0, 10.0, 30.0)
)

# ========== SUMMARIES ==========

# Overall TDD Workflow Summary
TDD_WORKFLOW_DURATION = Summary(
    'tdd_workflow_duration_seconds',
    'Complete TDD workflow duration'
)

TEST_ASSETS_PER_REQUIREMENT = Summary(
    'test_assets_per_requirement',
    'Number of test assets generated per requirement'
)

COVERAGE_IMPROVEMENT = Summary(
    'coverage_improvement_percentage',
    'Coverage improvement from initial to final measurement'
)


class TDDMetricsRecorder:
    """Helper class for recording TDD metrics."""

    @staticmethod
    def record_test_asset_generation(asset_type: str, count: int):
        """Record test asset generation event."""
        TEST_ASSETS_GENERATED.labels(asset_type=asset_type).inc(count)

    @staticmethod
    def record_test_asset_injection(req_id: str, total_assets: int):
        """Record test asset injection into context."""
        TEST_ASSETS_INJECTED.labels(req_id=req_id).inc(total_assets)

    @staticmethod
    def record_tdd_development(status: str):
        """Record TDD development completion."""
        TDD_DEV_COMPLETIONS.labels(status=status).inc()

    @staticmethod
    def record_test_execution(test_type: str, status: str, count: int = 1):
        """Record test execution result."""
        TEST_EXECUTIONS.labels(test_type=test_type, status=status).inc(count)

    @staticmethod
    def record_test_augmentation(reason: str, count: int = 1):
        """Record test augmentation cycle."""
        TEST_AUGMENTATIONS.labels(reason=reason).inc(count)

    @staticmethod
    def record_coverage(req_id: str, coverage_type: str, percentage: float):
        """Record coverage measurement."""
        A11_COVERAGE_CURRENT.labels(req_id=req_id, coverage_type=coverage_type).set(percentage)

    @staticmethod
    def record_coverage_gap(req_id: str, gap: float):
        """Record coverage gap."""
        A11_COVERAGE_GAP.labels(req_id=req_id).set(max(0.0, gap))

    @staticmethod
    def record_test_distribution(req_id: str, distribution: dict):
        """Record distribution of test assets."""
        for test_type, count in distribution.items():
            TEST_ASSET_DISTRIBUTION.labels(req_id=req_id, test_type=test_type).set(count)

    @staticmethod
    def record_pass_rate(req_id: str, phase: str, pass_rate: float):
        """Record test pass rate."""
        TDD_TEST_PASS_RATE.labels(req_id=req_id, phase=phase).set(pass_rate)

    @staticmethod
    def record_workflow_completion(status: str):
        """Record workflow completion."""
        TDD_WORKFLOW_COMPLETIONS.labels(status=status).inc()

    @staticmethod
    def record_cycle_duration(req_id: str, duration_seconds: float):
        """Record total TDD cycle duration."""
        TDD_CYCLE_DURATION_SECONDS.labels(req_id=req_id).set(duration_seconds)
        TDD_WORKFLOW_DURATION.observe(duration_seconds)

    @staticmethod
    def record_phase_duration(phase: str, req_id: str, duration_seconds: float):
        """Record individual phase duration."""
        if phase == "a7":
            A7_GENERATION_DURATION_SECONDS.labels(req_id=req_id).set(duration_seconds)
        elif phase == "a9":
            A9_TDD_DEVELOPMENT_DURATION_SECONDS.labels(req_id=req_id).set(duration_seconds)
        elif phase == "a11":
            A11_TEST_EXECUTION_DURATION_SECONDS.labels(req_id=req_id).set(duration_seconds)

    @staticmethod
    def record_test_execution_timing(test_type: str, duration_seconds: float):
        """Record individual test execution timing."""
        TEST_EXECUTION_DURATION.labels(test_type=test_type).observe(duration_seconds)
