"""
Mutation Metrics — Prometheus metrics for mutation testing.

Tracks mutation scores, survived mutations, and Critic mode improvements.
"""

import logging
from typing import Optional

logger = logging.getLogger(__name__)


class MutationMetrics:
    """Prometheus metrics for mutation testing."""

    def __init__(self):
        """Initialize metrics (requires prometheus_client to be installed)."""
        self.enabled = False

        try:
            from prometheus_client import Counter, Gauge, Histogram

            self.enabled = True

            # Gauges
            self.mutation_score = Gauge(
                "a11_mutation_score",
                "Mutation testing score (0-1)",
                labelnames=["project", "language"],
            )
            self.survived_mutations_count = Gauge(
                "a11_survived_mutations_count",
                "Number of survived mutations",
                labelnames=["project", "language"],
            )
            self.killed_mutations_count = Gauge(
                "a11_killed_mutations_count",
                "Number of killed mutations",
                labelnames=["project", "language"],
            )
            self.total_mutations_count = Gauge(
                "a11_total_mutations_count",
                "Total number of mutations",
                labelnames=["project", "language"],
            )

            # Counters
            self.critic_tests_generated_total = Counter(
                "a11_critic_tests_generated_total",
                "Total tests generated by Critic mode",
                labelnames=["project", "language"],
            )
            self.critic_mode_triggered_total = Counter(
                "a11_critic_mode_triggered_total",
                "Total times Critic mode was triggered",
                labelnames=["project", "language"],
            )

            # Histograms
            self.mutation_score_improvement = Histogram(
                "a11_mutation_score_improvement",
                "Score improvement after Critic mode (0-1)",
                labelnames=["project", "language"],
                buckets=(0.0, 0.05, 0.1, 0.15, 0.2, 0.5, 1.0),
            )
            self.critic_execution_time_ms = Histogram(
                "a11_critic_execution_time_ms",
                "Critic mode execution time in milliseconds",
                labelnames=["project", "language"],
                buckets=(100, 500, 1000, 2000, 5000, 10000, 30000),
            )

            logger.info("[MutationMetrics] Prometheus metrics enabled")

        except ImportError:
            logger.warning(
                "[MutationMetrics] prometheus_client not installed; metrics disabled"
            )

    def record_mutation_result(
        self,
        project: str,
        language: str,
        mutation_score: float,
        survived: int,
        killed: int,
        total: int,
    ) -> None:
        """
        Record mutation testing result.

        Args:
            project: Project identifier
            language: Programming language
            mutation_score: Score (0.0-1.0)
            survived: Number of survived mutations
            killed: Number of killed mutations
            total: Total number of mutations
        """
        if not self.enabled:
            return

        labels = {"project": project, "language": language}

        try:
            self.mutation_score.labels(**labels).set(mutation_score)
            self.survived_mutations_count.labels(**labels).set(survived)
            self.killed_mutations_count.labels(**labels).set(killed)
            self.total_mutations_count.labels(**labels).set(total)
        except Exception as e:
            logger.warning(f"[MutationMetrics] Failed to record result: {e}")

    def record_critic_tests_generated(
        self, project: str, language: str, count: int
    ) -> None:
        """
        Record tests generated by Critic mode.

        Args:
            project: Project identifier
            language: Programming language
            count: Number of tests generated
        """
        if not self.enabled:
            return

        labels = {"project": project, "language": language}

        try:
            for _ in range(count):
                self.critic_tests_generated_total.labels(**labels).inc()
        except Exception as e:
            logger.warning(
                f"[MutationMetrics] Failed to record critic tests: {e}"
            )

    def record_critic_mode_triggered(self, project: str, language: str) -> None:
        """
        Record Critic mode trigger event.

        Args:
            project: Project identifier
            language: Programming language
        """
        if not self.enabled:
            return

        labels = {"project": project, "language": language}

        try:
            self.critic_mode_triggered_total.labels(**labels).inc()
        except Exception as e:
            logger.warning(
                f"[MutationMetrics] Failed to record critic trigger: {e}"
            )

    def record_critic_improvement(
        self,
        project: str,
        language: str,
        improvement: float,
        execution_time_ms: float,
    ) -> None:
        """
        Record Critic mode improvement and timing.

        Args:
            project: Project identifier
            language: Programming language
            improvement: Score improvement (0.0-1.0)
            execution_time_ms: Execution time in milliseconds
        """
        if not self.enabled:
            return

        labels = {"project": project, "language": language}

        try:
            self.mutation_score_improvement.labels(**labels).observe(
                max(0, min(1.0, improvement))
            )
            self.critic_execution_time_ms.labels(**labels).observe(
                max(0, execution_time_ms)
            )
        except Exception as e:
            logger.warning(
                f"[MutationMetrics] Failed to record improvement: {e}"
            )
