"""
Test File Writer — Writes generated test cases to disk.

Handles Python and JavaScript/TypeScript test file generation and formatting.
"""

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


class TestFileWriter:
    """Writes generated test cases to test files."""

    def __init__(self, auto_format: bool = True):
        """
        Initialize the test file writer.

        Args:
            auto_format: Whether to auto-format generated code (default True)
        """
        self.auto_format = auto_format

    def write_tests(
        self,
        tests: list,
        project_path: str,
        language: str = "python",
        output_file: Optional[str] = None,
    ) -> str:
        """
        Write test cases to a file.

        Args:
            tests: List of test case dicts with 'test_code' key
            project_path: Root directory of the project
            language: 'python', 'javascript', 'typescript'
            output_file: Optional specific output file path

        Returns:
            Path to the written file
        """
        if not tests:
            logger.warning("[TestFileWriter] No tests to write")
            return ""

        project_path = Path(project_path).resolve()

        if language == "python":
            file_path = self._write_python_tests(tests, project_path, output_file)
        elif language in ("javascript", "typescript"):
            file_path = self._write_javascript_tests(tests, project_path, output_file)
        else:
            logger.error(f"[TestFileWriter] Unsupported language: {language}")
            return ""

        logger.info(f"[TestFileWriter] Wrote {len(tests)} tests to {file_path}")
        return str(file_path)

    def _write_python_tests(
        self, tests: list, project_path: Path, output_file: Optional[str] = None
    ) -> Path:
        """Write Python test cases."""
        # Determine output directory
        test_dir = project_path / "tests"
        test_dir.mkdir(parents=True, exist_ok=True)

        # Use provided filename or default
        if output_file:
            file_path = test_dir / output_file
        else:
            timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
            file_path = test_dir / f"test_critic_generated_{timestamp}.py"

        # Build file content
        content = self._build_python_test_file(tests)

        # Write file
        file_path.write_text(content, encoding="utf-8")
        logger.info(f"[TestFileWriter] Created Python test file: {file_path}")

        return file_path

    def _write_javascript_tests(
        self, tests: list, project_path: Path, output_file: Optional[str] = None
    ) -> Path:
        """Write JavaScript/TypeScript test cases."""
        # Determine output directory
        test_dir = project_path / "tests"
        test_dir.mkdir(parents=True, exist_ok=True)

        # Use provided filename or default
        if output_file:
            file_path = test_dir / output_file
        else:
            timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
            file_path = test_dir / f"test.critic.generated.{timestamp}.js"

        # Build file content
        content = self._build_javascript_test_file(tests)

        # Write file
        file_path.write_text(content, encoding="utf-8")
        logger.info(f"[TestFileWriter] Created JavaScript test file: {file_path}")

        return file_path

    def _build_python_test_file(self, tests: list) -> str:
        """Build Python test file content."""
        lines = [
            "# Auto-generated by A11 Critic Mode",
            f"# Generated: {datetime.now(timezone.utc).isoformat()}",
            "# These tests target survived mutations to improve mutation score.",
            "",
            "import pytest",
            "",
        ]

        for i, test in enumerate(tests):
            target = test.get("target", "unknown")
            mutator = test.get("mutator_type", "unknown")

            lines.append(f"# Mutation target: {target} ({mutator})")
            lines.append(f"# Mutation ID: {test.get('mutation_id', 'unknown')}")

            test_code = test.get("test_code", "")
            if test_code:
                # Ensure proper indentation
                test_lines = test_code.split("\n")
                for line in test_lines:
                    lines.append(line)
            else:
                lines.append("# Test code generation failed")

            lines.append("")

            if i < len(tests) - 1:
                lines.append("")

        return "\n".join(lines)

    def _build_javascript_test_file(self, tests: list) -> str:
        """Build JavaScript/TypeScript test file content."""
        lines = [
            "// Auto-generated by A11 Critic Mode",
            f"// Generated: {datetime.now(timezone.utc).isoformat()}",
            "// These tests target survived mutations to improve mutation score.",
            "",
        ]

        # Add common imports
        has_jest = False
        for test in tests:
            if "jest" in test.get("test_code", "").lower():
                has_jest = True
                break

        if has_jest:
            lines.append("describe('A11 Critic Mode Generated Tests', () => {")
            lines.append("")

            for test in tests:
                target = test.get("target", "unknown")
                mutator = test.get("mutator_type", "unknown")

                lines.append(f"  // Mutation target: {target} ({mutator})")
                lines.append(f"  // Mutation ID: {test.get('mutation_id', 'unknown')}")

                test_code = test.get("test_code", "")
                if test_code:
                    # Indent test code
                    test_lines = test_code.split("\n")
                    for line in test_lines:
                        if line.strip():
                            lines.append(f"  {line}")
                        else:
                            lines.append("")
                else:
                    lines.append("  // Test code generation failed")

                lines.append("")

            lines.append("});")
        else:
            for test in tests:
                target = test.get("target", "unknown")
                mutator = test.get("mutator_type", "unknown")

                lines.append(f"// Mutation target: {target} ({mutator})")
                lines.append(f"// Mutation ID: {test.get('mutation_id', 'unknown')}")

                test_code = test.get("test_code", "")
                if test_code:
                    lines.append(test_code)
                else:
                    lines.append("// Test code generation failed")

                lines.append("")

        return "\n".join(lines)
